#!/usr/bin/env bash

set -o nounset
set -o errexit

declare -r RPMBUILD=/home/rpmaker/rpmbuild
declare -r PROJECTS=$RPMBUILD/_projects
declare -r SOURCES=$RPMBUILD/SOURCES
declare -r SPECS=$RPMBUILD/SPECS

# Make symlinks from rpmbuild/_project/ to rpmbuild/
make_symlinks()
{
    local signature=$1; shift
    local name=${signature##*/}

    pushd $SPECS
    # Symlink .spec file
    ln -s ../_projects/$signature/${name}.spec ${name}.spec
    popd

    pushd $SOURCES
    # Go to project files, find all files that are not service.sh or .spec
    # and symlink them in SOURCES
    find ../_projects/$signature -type f \
        -not -name 'service.sh' \
        -not -name '*.spec' \
        -exec ln -s {} . \;
    popd
}

# Copy built src.rpm to project files
copy_src_rpm()
{
    rm -f $PROJECTS/$signature/*.src.rpm
    cp $RPMBUILD/SRPMS/${name}*.src.rpm $PROJECTS/$signature || true
}

run_prebuild_hook()
{
    local signature=$1; shift

    source $PROJECTS/$signature/service.sh
    if [ "$(type -t pkg_prebuild_hook)" = 'function' ]; then
        pkg_prebuild_hook
    fi
}

build()
{
    local signature=$1; shift
    local name=${signature##*/}

    make_symlinks $signature

    pushd $SPECS
    run_prebuild_hook $signature
    sudo dnf -y builddep ${name}.spec
    rpmbuild -ba "${name}.spec" || true
    popd

    copy_src_rpm $signature
}

build $@

