#!/usr/bin/env bash
# pwd -> /home/rpmaker/rpmbuild

set -o nounset
set -o errexit

# Make symlinks from project files
make_symlinks()
{
    local signature=$1; shift
    local name=${signature##*/}

    pushd SPECS
    # Symlink .spec file
    ln -s ../_projects/$signature/${name}.spec ${name}.spec
    popd

    pushd SOURCES
    # Symlink files that are neither prefixed with tmp_ nor named service.sh
    # or *.spec
    find ../_projects/$signature -type f \
        -not -path "../_projects/$signature/tmp_*" \
        -not -name 'service.sh' \
        -not -name '*.spec' \
        -exec ln -s {} . \;
    popd
}

# Copy built src.rpm to project files
copy_src_rpm()
{
    rm -f _projects/$signature/*.src.rpm
    cp SRPMS/${name}*.src.rpm _projects/$signature || true
}

run_prebuild_hook()
{
    local signature=$1; shift

    source _projects/$signature/service.sh
    if [ "$(type -t pkg_prebuild_hook)" = 'function' ]; then
        pkg_prebuild_hook
    fi
}

build()
{
    local signature=$1; shift
    local name=${signature##*/}

    make_symlinks $signature
    run_prebuild_hook $signature

    pushd SPECS
    sudo dnf -y builddep ${name}.spec
    rpmbuild -ba "${name}.spec" || true
    popd

    copy_src_rpm $signature
}

build $@

