#!/usr/bin/env bash
# pwd -> /home/rpmaker/rpmbuild

set -o nounset
set -o errexit

# Make symlinks from project files
make_symlinks()
{
    local signature=$1; shift
    local name=${signature##*/}

    pushd SPECS
    # Symlink .spec file
    ln -s ../_projects/$signature/${name}.spec ${name}.spec
    popd

    # Symlink files to rpmbuild/SOURCES
    pushd SOURCES
    find ../_projects/$signature -maxdepth 1 -type f \
        -not -name 'tmp_*' \
        -not -name 'service.sh' \
        -not -name '*.spec' \
        -exec ln -s {} . \;
    popd
}

# Copy all build results to project dir
copy_rpms()
{
    local output_dir=_projects/$signature/out

    # First clean output dir from previous builds
    rm -fr $output_dir; mkdir $output_dir

    cp {SRPMS,RPMS/**}/${name}*.rpm $output_dir
}

run_prebuild_hook()
{
    local signature=$1; shift

    source _projects/$signature/service.sh
    if [ "$(type -t pkg_prebuild_hook)" = 'function' ]; then
        pkg_prebuild_hook
    fi
}

build()
{
    local signature=$1; shift
    local name=${signature##*/}

    make_symlinks $signature
    run_prebuild_hook $signature

    pushd SPECS
    sudo dnf -y builddep ${name}.spec
    rpmbuild -ba "${name}.spec"
    popd

    copy_rpms $signature
}

build $@

